# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'ERPLibre package hr',
    'version': '12.0.1.0.0',
    'author': "TechnoLibre",
    'website': 'https://technolibre.ca',
    'license': 'AGPL-3',
    'category': 'Human ressources',
    'summary': 'INSTALL ERPLibre package hr',
    'description': """
ERPLibre package hr
===================

""",
    'depends': [
        # Custom ERPLibre
        'erplibre_base',

        'hr_expense_associate_with_customer',
        'hr_expense_tip',
        'res_partner_fix_group_by_company',

        # odoo/addons
        'hr',
        'hr_attendance',
        'hr_contract',
        'hr_expense',
        'hr_expense_check',
        'hr_gamification',
        'hr_holidays',
        'hr_maintenance',
        'hr_org_chart',
        'hr_payroll',
        'hr_payroll_account',
        'hr_recruitment',
        'hr_recruitment_survey',
        'hr_timesheet',
        'hr_timesheet_attendance',

        # addons/OCA_hr
        'hr_attendance_autoclose',
        'hr_attendance_geolocation',
        'hr_attendance_modification_tracking',
        'hr_attendance_reason',
        'hr_attendance_report_theoretical_time',
        'hr_attendance_rfid',
        'hr_calendar_rest_time',
        'hr_contract_currency',
        'hr_contract_document',
        'hr_contract_multi_job',
        'hr_contract_rate',
        'hr_course',
        'hr_employee_age',
        'hr_employee_birth_name',
        'hr_employee_calendar_planning',
        'hr_employee_display_own_info',
        'hr_employee_document',
        'hr_employee_emergency_contact',
        'hr_employee_firstname',
        'hr_employee_health',
        'hr_employee_id',
        'hr_employee_language',
        'hr_employee_medical_examination',
        'hr_employee_partner_external',
        'hr_employee_phone_extension',
        'hr_employee_relative',
        'hr_employee_service',
        'hr_employee_service_contract',
        'hr_employee_social_media',
        'hr_employee_ssn',
        'hr_expense_advance_clearing',
        'hr_expense_cancel',
        'hr_expense_invoice',
        'hr_expense_payment_difference',
        'hr_expense_petty_cash',
        'hr_expense_sequence',
        'hr_expense_tier_validation',
        'hr_experience',
        'hr_holidays_accrual_advanced',
        'hr_holidays_credit',
        'hr_holidays_hour',
        'hr_holidays_leave_auto_approve',
        'hr_holidays_leave_repeated',
        'hr_holidays_leave_request_wizard',
        'hr_holidays_length_validation',
        'hr_holidays_notify_employee_manager',
        'hr_holidays_public',
        'hr_holidays_settings',
        'hr_holidays_validity_date',
        'hr_job_category',
        'hr_payroll_cancel',
        'hr_payslip_change_state',
        'hr_period',
        'hr_skill',
        'hr_worked_days_from_timesheet',
        'resource_hook',

        # addons/Numigi_odoo-hr-addons
        'hr_contract_single_open',
        'hr_contract_wage_type',
        'hr_employee_private_wizard',
        'hr_employee_type',
        'hr_employee_type_private_wizard',
        'hr_event',
        'hr_expense_same_month',
        'hr_working_space',

        # Muk
        'muk_hr_utils',
    ],
    'data': [],
    'installable': True,
}
