# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'ERPLibre package accounting',
    'version': '12.0.1.0.0',
    'author': "TechnoLibre",
    'website': 'https://technolibre.ca',
    'license': 'AGPL-3',
    'category': 'stock',
    'summary': 'INSTALL ERPLibre package accounting',
    'description': """
ERPLibre package accounting
===========================

""",
    'depends': [
        # Custom ERPLibre
        'erplibre_base',

        # addons/OCA_account-budgeting
        # 'account_budget_oca',
        # 'account_budget_template',

        # OCA_account-closing
        # 'account_cutoff_accrual_base',
        # 'account_cutoff_accrual_dates',
        # 'account_cutoff_accrual_picking',
        # 'account_cutoff_base',
        # 'account_cutoff_prepaid',
        'account_fiscal_year_closing',
        # 'account_invoice_start_end_dates',
        # 'account_multicurrency_revaluation',

        # addons/OCA_account-consolidation
        # 'account_consolidation',

        # OCA_account-financial-reporting
        'account_export_csv',
        'account_financial_report',
        'account_tax_balance',
        'mis_builder_cash_flow',
        'partner_statement',

        # addons/OCA_account-financial-tools
        # 'account_asset_management',
        # 'account_balance_line',
        # TODO tester sutomatisation avec bank statement advanced + menu
        # 'account_bank_menu',
        # 'account_bank_statement_advanced',
        # 'account_chart_update',
        # 'account_check_deposit',
        # 'account_clearance_plan',
        # 'account_coa_menu',
        # 'account_cost_center',
        # 'account_document_reversal',
        # 'account_fiscal_month',
        # 'account_fiscal_position_vat_check',
        # 'account_fiscal_year',
        # 'account_group_menu',
        # 'account_invoice_constraint_chronology',
        # 'account_invoice_currency',
        # 'account_loan',
        # 'account_lock_date_update',
        # 'account_lock_to_date',
        # 'account_menu',
        # 'account_move_batch_validate',
        # 'account_move_budget',
        # 'account_move_chatter',
        # 'account_move_fiscal_month',
        # 'account_move_fiscal_year',
        # 'account_move_line_purchase_info',
        # 'account_move_line_tax_editable',
        # 'account_move_template',
        # 'account_netting',
        # 'account_partner_required',
        # 'account_payment_netting',
        # 'account_renumber',
        # 'account_spread_cost_revenue',
        # 'account_tag_menu',
        # 'account_type_menu',
        # 'account_voucher_print',
        # 'base_vat_optional_vies',

        # new to include and test
        # 'account_bank_statement_advanced',
        # 'account_bank_menu',

        # addons/OCA_account-fiscal-rule
        # 'account_fiscal_position_type',
        # 'account_fiscal_position_usage_group',
        # 'account_product_fiscal_classification',
        # 'account_product_fiscal_classification_test',

        # addons/OCA_account-invoice-reporting
        # 'account_invoice_comment_template',
        # 'account_invoice_line_report',
        # 'account_invoice_production_lot',
        # 'account_invoice_report_due_list',
        # 'account_invoice_report_grouped_by_picking',
        # 'account_invoice_report_hide_line',
        # 'account_invoice_report_payment_info',
        # 'account_reporting_weight',
        # 'base_comment_template',
        # 'partner_time_to_pay',

        # addons/OCA_account-invoicing
        # 'account_billing',
        # 'account_debitnote',
        # 'account_global_discount',
        # 'account_group_invoice_line',
        # 'account_invoice_analytic_search',
        # 'account_invoice_anglo_saxon_no_cogs_deferral',
        # 'account_invoice_approbation',
        # 'account_invoice_blocking',
        # 'account_invoice_change_currency',
        # 'account_invoice_check_total',
        # 'account_invoice_date_due',
        # 'account_invoice_fiscal_position_update',
        # 'account_invoice_fixed_discount',
        # 'account_invoice_force_number',
        # 'account_invoice_line_description',
        # 'account_invoice_line_sequence',
        # 'account_invoice_mass_sending',
        # 'account_invoice_merge',
        # 'account_invoice_pricelist',
        # 'account_invoice_pricelist_sale',
        # 'account_invoice_refund_link',
        # 'account_invoice_refund_reason',
        # 'account_invoice_reimbursable',
        # 'account_invoice_repair_link',
        # 'account_invoice_search_by_reference',
        # 'account_invoice_supplier_date',
        # 'account_invoice_supplier_ref_reuse',
        # 'account_invoice_supplier_ref_unique',
        # 'account_invoice_supplierinfo_update',
        # 'account_invoice_tax_note',
        # 'account_invoice_tax_required',
        # 'account_invoice_transmit_method',
        # 'account_invoice_transmit_method_substitution_rulev',
        # 'account_invoice_triple_discount',
        # 'account_invoice_validation_queued',
        # 'account_invoice_view_payment',
        # 'account_menu_invoice_refund',
        # 'account_payment_term_extension',
        # 'product_supplierinfo_for_customer_invoice',
        # 'purchase_batch_invoicing',
        # 'purchase_stock_picking_return_invoicing',
        # 'purchase_stock_picking_return_invoicing_force_invoiced',
        # 'sale_invoice_line_note',
        # 'sale_order_invoicing_grouping_criteria',
        # 'sale_order_invoicing_queued',
        # 'sale_timesheet_invoice_description',
        # 'stock_picking_invoicing',
        # 'stock_picking_return_refund_option',

        # addons/OCA_account-payment
        # 'account_cash_invoice',
        # 'account_check_printing_report_base',
        # 'account_check_printing_report_dlt103',
        # 'account_check_printing_report_sslm102',
        # 'account_check_report',
        # 'account_due_list',
        # 'account_due_list_aging_comment',
        # 'account_due_list_days_overdue',
        # 'account_due_list_payment_mode',
        # 'account_move_line_auto_reconcile_hook',
        # 'account_payment_credit_card',
        # 'account_payment_multi_deduction',
        # 'account_payment_residual_amount',
        # 'account_payment_return',
        # 'account_payment_return_import',
        # 'account_payment_return_import_iso20022',
        # 'account_payment_select_cost_account',
        # 'account_payment_show_invoice',
        # 'account_payment_widget_amount',
        # 'account_voucher_killer',
        # 'partner_aging',

        # addons/OCA_account-reconcile
        # 'account_banking_reconciliation',
        # 'account_mass_reconcile',
        # 'account_mass_reconcile_ref_deep_search',
        # 'account_move_base_import',
        # 'account_move_reconcile_helper',
        # 'account_move_so_import',
        # 'account_move_transactionid_import',
        # 'account_partner_reconcile',
        # 'account_reconcile_payment_order',
        # 'account_reconcile_reconciliation_date',
        # 'account_reconcile_restrict_partner_mismatch',
        # 'account_reconcile_rule',
        # 'account_set_reconcilable',
        # 'account_skip_bank_reconciliation',
        # 'bank_statement_foreign_currency',
        # 'base_transaction_id',

        # addons/OCA_bank-payment',
        # 'account_banking_make_deposit',
        # 'account_banking_mandate',
        # 'account_banking_mandate_sale',
        # 'account_banking_pain_base',
        # 'account_banking_sepa_credit_transfer',
        # 'account_banking_sepa_direct_debit',
        # 'account_payment_mode',
        # 'account_payment_order',
        # 'account_payment_order_return',
        # 'account_payment_partner',
        # 'account_payment_purchase',
        # 'account_payment_sale',

        # addons/OCA_bank_statement_import
        'account_bank_statement_import_camt_oca',
        'account_bank_statement_import_move_line',
        # TODO automatiser le import ofx, via import_online_##NEW RBC
        'account_bank_statement_import_ofx',
        'account_bank_statement_import_online',
        'account_bank_statement_import_online_paypal',
        'account_bank_statement_import_online_transferwise',
        'account_bank_statement_import_paypal',
        'account_bank_statement_import_split',
        'account_bank_statement_import_txt_xlsx',

        # addons/OCA_credit-control
        # 'account_credit_control',
        # 'account_credit_control_queue_job',
        # 'account_financial_risk',
        # 'account_payment_return_financial_risk',
        # 'partner_risk_insurance',
        # 'sale_financial_risk',
        # 'stock_financial_risk',

        # addons/OCA_currency
        # 'currency_monthly_rate',
        # 'currency_rate_inverted',
        # 'currency_rate_update',
        # 'currency_rate_update_oxr',
        # 'currency_rate_update_transferwise',
        # 'currency_rate_update_xe',

        # addons/OCA_margin-analysis
        # 'account_invoice_margin',
        # 'account_invoice_margin_sale',
        # 'product_replenishment_cost',
        # 'product_standard_margin',
        # 'sale_margin_delivered',
        # 'sale_margin_editor',
        # 'sale_margin_security',
        # 'sale_margin_sync',
        # 'sale_order_margin_percent',
        # 'sale_report_margin',

        # TODO mettre nom du repo addons pour ces modules
        'accounting_pdf_reports',
        'om_account_accountant',
        'om_account_asset',
        'om_account_budget',
    ],
    'data': [],
    'installable': True,
}
